### ISSUE TITLE
Autostart doesn't work

### ISSUE THREAD

**Issue by Bleuzen** [flathub/com.github.wwmm.pulseeffects#18]
PulseEffects has this nice option to "Start Service at Login".
But when I toggle it on with the flatpak version, it creates the autostart file in
`~/.var/app/com.github.wwmm.pulseeffects/config/autostart`
instead of
`~/.config/autostart`

Flatpak should have access to the real autostart directory to create the file there instead of in ~/.var.

Also within the autostart file,
`Exec=pulseeffects --gapplication-service`
has to be replaced with
`Exec=com.github.wwmm.pulseeffects --gapplication-service`

**Comment by TingPing** [comment]
Yea it can't work, you'll just have to manually add it for now.

There is discussion about Flatpak exposing this but no work has been done on it.

**Comment by wwmm** [comment]
The `Exec=com.github.wwmm.pulseeffects --gapplication-service` will require changes in PE sources. At this moment the `exec` field is hardcoded. It would be necessary to patch PE sources before building

**Comment by iQmam0n** [comment]
I was able to start with the following change.
`~/.config/autostart/pulseeffects-service.desktop`

from:
`Exec=pulseeffects --gapplication-service`
to:
`Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=pulseeffects com.github.wwmm.pulseeffects --gapplication-service`

**Comment by AsavarTzeth** [comment]
@iQmamOn Yes that is how you add it manually, for now.

**Comment by vchernin** [comment]
[This is fixed in EasyEffects, successor to PulseEffects.](https://github.com/flathub/com.github.wwmm.easyeffects/issues/3#issuecomment-922118878) I have no plans to try to backport the fix here, I think solving https://github.com/flatpak/xdg-desktop-portal/issues/579 is a better use of time as that means the background portal could be used on the host.

**Comment by 1player** [comment]
This can be closed, I've been using EasyEffects with autostart for months and it's never failed me.
