### ISSUE TITLE
Please update to 4.5.0

### ISSUE THREAD

**Issue by logix2** [flathub/com.github.wwmm.pulseeffects#23]
Can you please update PulseEffects to version 4.5.0? It adds a cool feature which allows  making a preset autoload when an input or output device is plugged in the system.

**Comment by AsavarTzeth** [comment]
It took me most of my Saturday, but I managed to get everything up-to-date :)
All that remains is final testing and ensuring everything builds on all architectures.

**Comment by logix2** [comment]
Thank you!
