### ISSUE TITLE
Needs a screenshot 

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.github.wwmm.pulseeffects#3]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

**Comment by AsavarTzeth** [comment]
AppData is handled upstream and there are screenshots. If you don't see them that is another issue which I currently don't have an answer for.

**Comment by AsavarTzeth** [comment]
There are screenshots available in the [appdata](https://github.com/wwmm/pulseeffects/blob/master/data/com.github.wwmm.pulseeffects.appdata.xml.in#L39).

I understand you are running Endless OS? I was sort of able to reproduce this on Endless OS. There are no screenshots, initially but if you wait and reload the page they do appear.
