### ISSUE TITLE
 minimize t system tray 

### ISSUE THREAD

**Issue by andresgarcia0313** [flathub/com.github.wwmm.pulseeffects#32]
please add the option to minimize to system tray especially for the flatpak package

you are incredible
pulseeffects is a wonder

**Comment by AsavarTzeth** [comment]
I am not the PulseEffects developer. Please report this upstream. You may find that here:
https://github.com/wwmm/pulseeffects/issues

Do note that PulseEffects is already capable of running in the background and can be brought back by clicking the regular app icon.

Adding systray support would not really add anything. It's a legacy way of doing things.
