### ISSUE TITLE
Update: new version of pulse effect released (4.6.9)

### ISSUE THREAD

**Issue by savbran** [flathub/com.github.wwmm.pulseeffects#35]
Please, can you update the flatpak? Thanks in advance.
https://github.com/wwmm/pulseeffects/releases

**Comment by savbran** [comment]
https://github.com/wwmm/pulseeffects/releases

**Comment by AsavarTzeth** [comment]
I'm well aware, but thank you anyhow! Time has been in short supply this holiday season. Hopefully I will get it up soon.

**Comment by AsavarTzeth** [comment]
Version 4.7.0 is now published.
