### ISSUE TITLE
The .desktop file in flatpak tries to run "pulseeffects" directly instead of through flatpak

### ISSUE THREAD

**Issue by promi** [flathub/com.github.wwmm.pulseeffects#39]
When installing via flatpak (on Debian sid with GNOME), after restarting the desktop environment a menu item is shown for PulseEffects, but it does not work.

When I look at the .desktop file it has just "pulseeffects" as its run command, but on the command line I have to type:

flatpak run com.github.wwmm.pulseeffects

Is the .desktop file broken?

**Comment by AsavarTzeth** [comment]
That does seem broken. It should use `Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=pulseeffects com.github.wwmm.pulseeffects` (for x86).

You may have already tried this but could you uninstall the app and verify that the .desktop file is removed? If not, remove it manually and reinstall. I have a vague memory of something similar happening to me at some point and I think I solved it that way.

**Comment by wwmm** [comment]
Ideally it would be good if the flatpak building process patched our `.desktop' files in the way that they need to be to be when used under flatpak. But if this is complicated for whatever reason we may consider adding to PulseEffects sources additional desktop files that work in Flatpak. But even them the building process would have to at least choosing the right files.

**Comment by AsavarTzeth** [comment]
The build process, specifically `flatpak-builder` already does that and have supported this for years; essentially from the beginning.

I have no idea why it has broken in this particular case.
