### ISSUE TITLE
Missing permission to access RTKit

### ISSUE THREAD

**Issue by LeonardKoenig** [flathub/com.github.wwmm.pulseeffects#45]
In order to talk to RTKit this Flatpak needs access to the the DBus service via the system bus:

```
$ flatpak --user override --system-talk-name=org.freedesktop.RealtimeKit1 com.github.wwmm.pulseeffects
```

Otherwise you'll get the following error on startup:

```
rtkit: Failed to connect to system bus: Could not connect: No such file or directory```

**Comment by AsavarTzeth** [comment]
That won't work. Its a well known issue. See https://github.com/flatpak/xdg-desktop-portal/issues/355

**Comment by wwmm** [comment]
Once I finish the work I am doing at https://github.com/wwmm/pulseeffects/tree/gtk4 we won't need RealtimeKit anymore. Besides the port to GTKMM4 I am also moving our effects pipeline from GStreamer to native PipeWire filters. One of the advantages of doing so is that PipeWire manages the cpu priorities for its filters. So I won't have to do this myself as it has to be done when doing the processing outside of PipeWire.

**Comment by gasinvein** [comment]
FYI a realtimekit portal was proposed in flatpak/xdg-desktop-portal#600
